name: Health check

on:
  schedule:
    - cron: '14 13 * * *'

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the pokédex URI
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: http://pokedex-banaanihillo.herokuapp.com/
      
      - uses: actions/checkout@v2
      
      - name: Notify on successful health check
        if: ${{success()}}
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{secrets.TELEGRAM_TO}}
          token: ${{secrets.TELEGRAM_TOKEN}}
          message: Pokédex health check successful

